"""initial schema

Revision ID: da1ca0c388e1
Revises:
Create Date: 2026-04-12 15:23:01.082010

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "da1ca0c388e1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
